// filters.js

const filters = [
    {
    id: "employee",
    name: "Employee",
    options: 
      [
        { value: "0-1 employees", label: "0-1" },
        { value: "2-10 employees", label: "2-10" },
        { value: "11-50 employees", label: "11-50" },
        { value: "51-200 employees", label: "51-200" },
        { value: "201-500 employees", label: "201-500" },
        { value: "501-1,000 employees", label: "501-1,000" },
        { value: "1,001-5,000 employees", label: "1,001-5,000" },
        { value: "5,001-10,000 employees", label: "5,001-10,000" },
        { value: "10,001+ employees", label: "10,001+" }
      ],
    },
    {
      id: "industry",
      name: "Industry",
      options: [
        { value: "Advertising/Media/Publishing", label: "Advertising/Media/Publishing" },
        { value: "Aerospace and Aviation", label: "Aerospace and Aviation" },
        { value: "Agriculture and Forestry", label: "Agriculture and Forestry" },
        { value: "Banking/Accounting/Financial", label: "Banking/Accounting/Financial" },
        { value: "Business Services", label: "Business Services" },
        { value: "Computer and Technology", label: "Computer and Technology" },
        { value: "Education", label: "Education" },
        { value: "Energy & Utilities", label: "Energy & Utilities" },
        { value: "Entertainment/Travel/Hospitality", label: "Entertainment/Travel/Hospitality" },
        { value: "Food and Beverage", label: "Food and Beverage" },
        { value: "Government", label: "Government" },
        { value: "Healthcare", label: "Healthcare" },
        { value: "Human Resources", label: "Human Resources" },
        { value: "IT", label: "IT" },
        { value: "Legal Solutions", label: "Legal Solutions" },
        { value: "Manufacturing", label: "Manufacturing" },
        { value: "Marketing and Advertising", label: "Marketing and Advertising" },
        { value: "Media and Entertainment", label: "Media and Entertainment" },
        { value: "Non Profit Organizations", label: "Non Profit Organizations" },
        { value: "Other", label: "Other" },
        { value: "Real Estate", label: "Real Estate" },
        { value: "Renewables & Environment", label: "Renewables & Environment" },
        { value: "Retail and Wholesale", label: "Retail and Wholesale" },
        { value: "Standard Industries", label: "Standard Industries" },
        { value: "Telecommunications", label: "Telecommunications" },
        { value: "Transportation and Shipping", label: "Transportation and Shipping" }
      ]
    },    
    {
      id: "title",
      name: "Job Title",
      options: [
        
      ],
    },
    {
      id: "region",
      name: "Region",
      options: [
        { value: "Africa", label: "Africa" },
        { value: "Asia", label: "Asia" },
        { value: "Benelux", label: "Benelux" },
        { value: "DACH", label: "DACH" },
        { value: "Europe", label: "Europe" },
        { value: "MENA", label: "MENA" },
        { value: "Nordics", label: "Nordics" },
        { value: "North America", label: "North America" },
        { value: "Oceania", label: "Oceania" },
        { value: "South America", label: "South America" },

      ],
    },
    {
      id: "country",
      name: "Country",
      options: [
        { value: "Afghanistan", label: "Afghanistan" },
        { value: "Albania", label: "Albania" },
        { value: "Algeria", label: "Algeria" },
        { value: "Andorra", label: "Andorra" },
        { value: "Angola", label: "Angola" },
        { value: "Argentina", label: "Argentina" },
        { value: "Armenia", label: "Armenia" },
        { value: "Australia", label: "Australia" },
        { value: "Austria", label: "Austria" },
        { value: "Azerbaijan", label: "Azerbaijan" },
        { value: "Bahrain", label: "Bahrain" },
        { value: "Bangladesh", label: "Bangladesh" },
        { value: "Belarus", label: "Belarus" },
        { value: "Belgium", label: "Belgium" },
        { value: "Bolivia", label: "Bolivia" },
        { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
        { value: "Botswana", label: "Botswana" },
        { value: "Brazil", label: "Brazil" },
        { value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
        { value: "British Virgin Islands", label: "British Virgin Islands" },
        { value: "Brunei", label: "Brunei" },
        { value: "Bulgaria", label: "Bulgaria" },
        { value: "Cambodia", label: "Cambodia" },
        { value: "Cameroon", label: "Cameroon" },
        { value: "Canada", label: "Canada" },
        { value: "Cayman Islands", label: "Cayman Islands" },
        { value: "Chile", label: "Chile" },
        { value: "China", label: "China" },
        { value: "Colombia", label: "Colombia" },
        { value: "Costa Rica", label: "Costa Rica" },
        { value: "Cote Dlvoire", label: "Cote Dlvoire" },
        { value: "Croatia", label: "Croatia" },
        { value: "Cyprus", label: "Cyprus" },
        { value: "Czechia", label: "Czechia" },
        { value: "Denmark", label: "Denmark" },
        { value: "Dominican Republic", label: "Dominican Republic" },
        { value: "Ecuador", label: "Ecuador" },
        { value: "Egypt", label: "Egypt" },
        { value: "El Salvador", label: "El Salvador" },
        { value: "Estonia", label: "Estonia" },
        { value: "Ethiopia", label: "Ethiopia" },
        { value: "Fiji", label: "Fiji" },
        { value: "Finland", label: "Finland" },
        { value: "France", label: "France" },
        { value: "French Polynesia", label: "French Polynesia" },
        { value: "Georgia", label: "Georgia" },
        { value: "Germany", label: "Germany" },
        { value: "Ghana", label: "Ghana" },
        { value: "Greece", label: "Greece" },
        { value: "Guatemala", label: "Guatemala" },
        { value: "Honduras", label: "Honduras" },
        { value: "Hong Kong", label: "Hong Kong" },
        { value: "Hungary", label: "Hungary" },
        { value: "Iceland", label: "Iceland" },
        { value: "India", label: "India" },
        { value: "Indonesia", label: "Indonesia" },
        { value: "Iran", label: "Iran" },
        { value: "Iraq", label: "Iraq" },
        { value: "Ireland", label: "Ireland" },
        { value: "Israel", label: "Israel" },
        { value: "Italy", label: "Italy" },
        { value: "Ivory Coast", label: "Ivory Coast" },
        { value: "Jamaica", label: "Jamaica" },
        { value: "Japan", label: "Japan" },
        { value: "Jordan", label: "Jordan" },
        { value: "Kazakhstan", label: "Kazakhstan" },
        { value: "Kenya", label: "Kenya" },
        { value: "Kuwait", label: "Kuwait" },
        { value: "Laos", label: "Laos" },
        { value: "Latvia", label: "Latvia" },
        { value: "Lebanon", label: "Lebanon" },
        { value: "Libya", label: "Libya" },
        { value: "Liechtenstein", label: "Liechtenstein" },
        { value: "Lithuania", label: "Lithuania" },
        { value: "Luxembourg", label: "Luxembourg" },
        { value: "Macau", label: "Macau" },
        { value: "Malaysia", label: "Malaysia" },
        { value: "Malta", label: "Malta" },
        { value: "Mauritius", label: "Mauritius" },
        { value: "Mexico", label: "Mexico" },
        { value: "Monaco", label: "Monaco" },
        { value: "Morocco", label: "Morocco" },
        { value: "Myanmar", label: "Myanmar" },
        { value: "Namibia", label: "Namibia" },
        { value: "Nepal", label: "Nepal" },
        { value: "Netherlands", label: "Netherlands" },
        { value: "New Zealand", label: "New Zealand" },
        { value: "Nicaragua", label: "Nicaragua" },
        { value: "Nigeria", label: "Nigeria" },
        { value: "North Korea", label: "North Korea" },
        { value: "North Macedonia", label: "North Macedonia" },
        { value: "Norway", label: "Norway" },
        { value: "Oman", label: "Oman" },
        { value: "Pakistan", label: "Pakistan" },
        { value: "Panama", label: "Panama" },
        { value: "Papua New Guinea", label: "Papua New Guinea" },
        { value: "Paraguay", label: "Paraguay" },
        { value: "Peru", label: "Peru" },
        { value: "Philippines", label: "Philippines" },
        { value: "Poland", label: "Poland" },
        { value: "Portugal", label: "Portugal" },
        { value: "Puerto Rico", label: "Puerto Rico" },
        { value: "Qatar", label: "Qatar" },
        { value: "Romania", label: "Romania" },
        { value: "Russia", label: "Russia" },
        { value: "Rwanda", label: "Rwanda" },
        { value: "Saudi Arabia", label: "Saudi Arabia" },
        { value: "Senegal", label: "Senegal" },
        { value: "Serbia", label: "Serbia" },
        { value: "Seychelles", label: "Seychelles" },
        { value: "Singapore", label: "Singapore" },
        { value: "Slovakia", label: "Slovakia" },
        { value: "Slovenia", label: "Slovenia" },
        { value: "South Africa", label: "South Africa" },
        { value: "South Korea", label: "South Korea" },
        { value: "Spain", label: "Spain" },
        { value: "Sri Lanka", label: "Sri Lanka" },
        { value: "Sudan", label: "Sudan" },
        { value: "Sweden", label: "Sweden" },
        { value: "Switzerland", label: "Switzerland" },
        { value: "Syria", label: "Syria" },
        { value: "Taiwan", label: "Taiwan" },
        { value: "Tanzania", label: "Tanzania" },
        { value: "Thailand", label: "Thailand" },
        { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
        { value: "Tunisia", label: "Tunisia" },
        { value: "Turkey", label: "Turkey" },
        { value: "Turkmenistan", label: "Turkmenistan" },
        { value: "Uganda", label: "Uganda" },
        { value: "Ukraine", label: "Ukraine" },
        { value: "United Arab Emirates", label: "United Arab Emirates" },
        { value: "United Kingdom", label: "United Kingdom" },
        { value: "United States", label: "United States" },
        { value: "Uruguay", label: "Uruguay" },
        { value: "Venezuela", label: "Venezuela" },
        { value: "Vietnam", label: "Vietnam" },
        { value: "Yemen", label: "Yemen" },
        { value: "Zambia", label: "Zambia" },
        { value: "Zimbabwe", label: "Zimbabwe" }
      ],
    },
    {
      id: "state",
      name: "State",
      options: [
        // States could be dynamically loaded based on the selected country
        { value: "California", label: "California" },
        { value: "New York", label: "New York" },
        // Add more states as needed
      ],
    },
    {
      id: "city",
      name: "City",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Los Angeles", label: "Los Angeles" },
        { value: "New York City", label: "New York City" },
        // Add more cities as needed
      ],
    },
    {
      id: "sub_industry",
      name: "sub_industry",
      options: [
{ value:'Chiropractors', label:'Chiropractors' },
{ value:'Defense and Space Manufacturing', label:'Defense and Space Manufacturing' },
{ value:'Optometrists', label:'Optometrists' },
{ value:'Computer Hardware Manufacturing', label:'Computer Hardware Manufacturing' },
{ value:'Software Development', label:'Software Development' },
{ value:'Computer Networking Products', label:'Computer Networking Products' },
{ value:'Transportation Equipment Manufacturing', label:'Transportation Equipment Manufacturing' },
{ value:'Technology, Information and Internet', label:'Technology, Information and Internet' },
{ value:'Physical, Occupational and Speech Therapists', label:'Physical, Occupational and Speech Therapists' },
{ value:'Semiconductor Manufacturing', label:'Semiconductor Manufacturing' },
{ value:'Telecommunications', label:'Telecommunications' },
{ value:'Law Practice', label:'Law Practice' },
{ value:'Housing Programs', label:'Housing Programs' },
{ value:'Legal Services', label:'Legal Services' },
{ value:'Business Consulting and Services', label:'Business Consulting and Services' },
{ value:'Biotechnology Research', label:'Biotechnology Research' },
{ value:'Family Planning Centers', label:'Family Planning Centers' },
{ value:'Medical Practices', label:'Medical Practices' },
{ value:'Transportation Programs', label:'Transportation Programs' },
{ value:'Hospitals and Health Care', label:'Hospitals and Health Care' },
{ value:'Utilities Administration', label:'Utilities Administration' },
{ value:'Pharmaceutical Manufacturing', label:'Pharmaceutical Manufacturing' },
{ value:'Outpatient Care Centers', label:'Outpatient Care Centers' },
{ value:'Veterinary Services', label:'Veterinary Services' },
{ value:'Medical Equipment Manufacturing', label:'Medical Equipment Manufacturing' },
{ value:'Space Research and Technology', label:'Space Research and Technology' },
{ value:'Motor Vehicle Parts Manufacturing', label:'Motor Vehicle Parts Manufacturing' },
{ value:'Personal Care Product Manufacturing', label:'Personal Care Product Manufacturing' },
{ value:'Retail Apparel and Fashion', label:'Retail Apparel and Fashion' },
{ value:'Sporting Goods Manufacturing', label:'Sporting Goods Manufacturing' },
{ value:'Tobacco Manufacturing', label:'Tobacco Manufacturing' },
{ value:'Medical and Diagnostic Laboratories', label:'Medical and Diagnostic Laboratories' },
{ value:'Retail Groceries', label:'Retail Groceries' },
{ value:'Food and Beverage Manufacturing', label:'Food and Beverage Manufacturing' },
{ value:'Oil Extraction', label:'Oil Extraction' },
{ value:'Computers and Electronics Manufacturing', label:'Computers and Electronics Manufacturing' },
{ value:'Natural Gas Extraction', label:'Natural Gas Extraction' },
{ value:'Manufacturing', label:'Manufacturing' },
{ value:'Furniture and Home Furnishings Manufacturing', label:'Furniture and Home Furnishings Manufacturing' },
{ value:'Home Health Care Services', label:'Home Health Care Services' },
{ value:'Retail', label:'Retail' },
{ value:'Embedded Software Products', label:'Embedded Software Products' },
{ value:'Entertainment Providers', label:'Entertainment Providers' },
{ value:'Mobile Computing Software Products', label:'Mobile Computing Software Products' },
{ value:'Gambling Facilities and Casinos', label:'Gambling Facilities and Casinos' },
{ value:'Ambulance Services', label:'Ambulance Services' },
{ value:'Desktop Computing Software Products', label:'Desktop Computing Software Products' },
{ value:'IT System Custom Software Development', label:'IT System Custom Software Development' },
{ value:'Travel Arrangements', label:'Travel Arrangements' },
{ value:'IT System Operations and Maintenance', label:'IT System Operations and Maintenance' },
{ value:'Hospitality', label:'Hospitality' },
{ value:'IT System Installation and Disposal', label:'IT System Installation and Disposal' },
{ value:'Restaurants', label:'Restaurants' },
{ value:'IT System Training and Support', label:'IT System Training and Support' },
{ value:'Hospitals', label:'Hospitals' },
{ value:'Spectator Sports', label:'Spectator Sports' },
{ value:'IT System Data Services', label:'IT System Data Services' },
{ value:'Food and Beverage Services', label:'Food and Beverage Services' },
{ value:'IT System Testing and Evaluation', label:'IT System Testing and Evaluation' },
{ value:'Movies, Videos, and Sound', label:'Movies, Videos, and Sound' },
{ value:'Broadcast Media Production and Distribution', label:'Broadcast Media Production and Distribution' },
{ value:'Museums, Historical Sites, and Zoos', label:'Museums, Historical Sites, and Zoos' },
{ value:'Artists and Writers', label:'Artists and Writers' },
{ value:'Performing Arts', label:'Performing Arts' },
{ value:'Recreational Facilities', label:'Recreational Facilities' },
{ value:'Banking', label:'Banking' },
{ value:'Insurance', label:'Insurance' },
{ value:'Nursing Homes and Residential Care Facilities', label:'Nursing Homes and Residential Care Facilities' },
{ value:'Financial Services', label:'Financial Services' },
{ value:'Real Estate', label:'Real Estate' },
{ value:'Investment Banking', label:'Investment Banking' },
{ value:'Investment Management', label:'Investment Management' },
{ value:'Accounting', label:'Accounting' },
{ value:'Construction', label:'Construction' },
{ value:'Wholesale Building Materials', label:'Wholesale Building Materials' },
{ value:'Architecture and Planning', label:'Architecture and Planning' },
{ value:'Civil Engineering', label:'Civil Engineering' },
{ value:'Internet News', label:'Internet News' },
{ value:'Aviation and Aerospace Component Manufacturing', label:'Aviation and Aerospace Component Manufacturing' },
{ value:'Blogs', label:'Blogs' },
{ value:'Motor Vehicle Manufacturing', label:'Motor Vehicle Manufacturing' },
{ value:'Interior Design', label:'Interior Design' },
{ value:'Chemical Manufacturing', label:'Chemical Manufacturing' },
{ value:'Social Networking Platforms', label:'Social Networking Platforms' },
{ value:'Machinery Manufacturing', label:'Machinery Manufacturing' },
{ value:'Household and Institutional Furniture Manufacturing', label:'Household and Institutional Furniture Manufacturing' },
{ value:'Business Intelligence Platforms', label:'Business Intelligence Platforms' },
{ value:'Mining', label:'Mining' },
{ value:'Business Content', label:'Business Content' },
{ value:'Oil and Gas', label:'Oil and Gas' },
{ value:'Data Security Software Products', label:'Data Security Software Products' },
{ value:'Shipbuilding', label:'Shipbuilding' },
{ value:'Utilities', label:'Utilities' },
{ value:'Mobile Gaming Apps', label:'Mobile Gaming Apps' },
{ value:'Textile Manufacturing', label:'Textile Manufacturing' },
{ value:'Internet Publishing', label:'Internet Publishing' },
{ value:'Paper and Forest Product Manufacturing', label:'Paper and Forest Product Manufacturing' },
{ value:'Media and Telecommunications', label:'Media and Telecommunications' },
{ value:'Railroad Equipment Manufacturing', label:'Railroad Equipment Manufacturing' },
{ value:'Blockchain Services', label:'Blockchain Services' },
{ value:'Farming', label:'Farming' },
{ value:'Services for the Elderly and Disabled', label:'Services for the Elderly and Disabled' },
{ value:'Ranching', label:'Ranching' },
{ value:'Dairy Product Manufacturing', label:'Dairy Product Manufacturing' },
{ value:'Office Furniture and Fixtures Manufacturing', label:'Office Furniture and Fixtures Manufacturing' },
{ value:'Fisheries', label:'Fisheries' },
{ value:'Community Services', label:'Community Services' },
{ value:'Primary and Secondary Education', label:'Primary and Secondary Education' },
{ value:'Higher Education', label:'Higher Education' },
{ value:'Education Administration Programs', label:'Education Administration Programs' },
{ value:'Research Services', label:'Research Services' },
{ value:'Mattress and Blinds Manufacturing', label:'Mattress and Blinds Manufacturing' },
{ value:'Armed Forces', label:'Armed Forces' },
{ value:'Legislative Offices', label:'Legislative Offices' },
{ value:'Administration of Justice', label:'Administration of Justice' },
{ value:'International Affairs', label:'International Affairs' },
{ value:'Emergency and Relief Services', label:'Emergency and Relief Services' },
{ value:'Government Administration', label:'Government Administration' },
{ value:'Executive Offices', label:'Executive Offices' },
{ value:'Law Enforcement', label:'Law Enforcement' },
{ value:'Vocational Rehabilitation Services', label:'Vocational Rehabilitation Services' },
{ value:'Public Safety', label:'Public Safety' },
{ value:'Public Policy Offices', label:'Public Policy Offices' },
{ value:'Advertising Services', label:'Advertising Services' },
{ value:'Child Day Care Services', label:'Child Day Care Services' },
{ value:'Newspaper Publishing', label:'Newspaper Publishing' },
{ value:'Performing Arts and Spectator Sports', label:'Performing Arts and Spectator Sports' },
{ value:'Book and Periodical Publishing', label:'Book and Periodical Publishing' },
{ value:'Printing Services', label:'Printing Services' },
{ value:'Information Services', label:'Information Services' },
{ value:'Libraries', label:'Libraries' },
{ value:'Theater Companies', label:'Theater Companies' },
{ value:'Environmental Services', label:'Environmental Services' },
{ value:'Freight and Package Transportation', label:'Freight and Package Transportation' },
{ value:'Dance Companies', label:'Dance Companies' },
{ value:'Individual and Family Services', label:'Individual and Family Services' },
{ value:'Religious Institutions', label:'Religious Institutions' },
{ value:'Civic and Social Organizations', label:'Civic and Social Organizations' },
{ value:'Consumer Services', label:'Consumer Services' },
{ value:'Circuses and Magic Shows', label:'Circuses and Magic Shows' },
{ value:'Truck Transportation', label:'Truck Transportation' },
{ value:'Warehousing and Storage', label:'Warehousing and Storage' },
{ value:'Sports Teams and Clubs', label:'Sports Teams and Clubs' },
{ value:'Airlines and Aviation', label:'Airlines and Aviation' },
{ value:'Maritime Transportation', label:'Maritime Transportation' },
{ value:'Racetracks', label:'Racetracks' },
{ value:'IT Services and IT Consulting', label:'IT Services and IT Consulting' },
{ value:'Market Research', label:'Market Research' },
{ value:'Public Relations and Communications Services', label:'Public Relations and Communications Services' },
{ value:'Design Services', label:'Design Services' },
{ value:'Non-profit Organizations', label:'Non-profit Organizations' },
{ value:'Fundraising', label:'Fundraising' },
{ value:'Strategic Management Services', label:'Strategic Management Services' },
{ value:'Writing and Editing', label:'Writing and Editing' },
{ value:'Staffing and Recruiting', label:'Staffing and Recruiting' },
{ value:'Wholesale Motor Vehicles and Parts', label:'Wholesale Motor Vehicles and Parts' },
{ value:'Professional Training and Coaching', label:'Professional Training and Coaching' },
{ value:'Venture Capital and Private Equity Principals', label:'Venture Capital and Private Equity Principals' },
{ value:'Political Organizations', label:'Political Organizations' },
{ value:'Translation and Localization', label:'Translation and Localization' },
{ value:'Computer Games', label:'Computer Games' },
{ value:'Events Services', label:'Events Services' },
{ value:'Retail Art Supplies', label:'Retail Art Supplies' },
{ value:'Museums', label:'Museums' },
{ value:'Appliances, Electrical, and Electronics Manufacturing', label:'Appliances, Electrical, and Electronics Manufacturing' },
{ value:'Online Audio and Video Media', label:'Online Audio and Video Media' },
{ value:'Wholesale Furniture and Home Furnishings', label:'Wholesale Furniture and Home Furnishings' },
{ value:'Historical Sites', label:'Historical Sites' },
{ value:'Nanotechnology Research', label:'Nanotechnology Research' },
{ value:'Retail Art Dealers', label:'Retail Art Dealers' },
{ value:'Musicians', label:'Musicians' },
{ value:'Zoos and Botanical Gardens', label:'Zoos and Botanical Gardens' },
{ value:'Transportation, Logistics, Supply Chain and Storage', label:'Transportation, Logistics, Supply Chain and Storage' },
{ value:'Plastics Manufacturing', label:'Plastics Manufacturing' },
{ value:'Computer and Network Security', label:'Computer and Network Security' },
{ value:'Wireless Services', label:'Wireless Services' },
{ value:'Amusement Parks and Arcades', label:'Amusement Parks and Arcades' },
{ value:'Alternative Dispute Resolution', label:'Alternative Dispute Resolution' },
{ value:'Security and Investigations', label:'Security and Investigations' },
{ value:'Facilities Services', label:'Facilities Services' },
{ value:'Outsourcing and Offshoring Consulting', label:'Outsourcing and Offshoring Consulting' },
{ value:'Wellness and Fitness Services', label:'Wellness and Fitness Services' },
{ value:'Alternative Medicine', label:'Alternative Medicine' },
{ value:'Media Production', label:'Media Production' },
{ value:'Animation and Post-production', label:'Animation and Post-production' },
{ value:'Leasing Non-residential Real Estate', label:'Leasing Non-residential Real Estate' },
{ value:'Capital Markets', label:'Capital Markets' },
{ value:'Wholesale Photography Equipment and Supplies', label:'Wholesale Photography Equipment and Supplies' },
{ value:'Think Tanks', label:'Think Tanks' },
{ value:'Philanthropic Fundraising Services', label:'Philanthropic Fundraising Services' },
{ value:'Golf Courses and Country Clubs', label:'Golf Courses and Country Clubs' },
{ value:'E-Learning Providers', label:'E-Learning Providers' },
{ value:'Wholesale', label:'Wholesale' },
{ value:'Wholesale Computer Equipment', label:'Wholesale Computer Equipment' },
{ value:'Skiing Facilities', label:'Skiing Facilities' },
{ value:'Wholesale Import and Export', label:'Wholesale Import and Export' },
{ value:'Industrial Machinery Manufacturing', label:'Industrial Machinery Manufacturing' },
{ value:'Photography', label:'Photography' },
{ value:'Human Resources Services', label:'Human Resources Services' },
{ value:'Retail Office Equipment', label:'Retail Office Equipment' },
{ value:'Mental Health Care', label:'Mental Health Care' },
{ value:'Graphic Design', label:'Graphic Design' },
{ value:'International Trade and Development', label:'International Trade and Development' },
{ value:'Beverage Manufacturing', label:'Beverage Manufacturing' },
{ value:'Accommodation and Food Services', label:'Accommodation and Food Services' },
{ value:'Wholesale Metals and Minerals', label:'Wholesale Metals and Minerals' },
{ value:'Retail Luxury Goods and Jewelry', label:'Retail Luxury Goods and Jewelry' },
{ value:'Glass, Ceramics and Concrete Manufacturing', label:'Glass, Ceramics and Concrete Manufacturing' },
{ value:'Packaging and Containers Manufacturing', label:'Packaging and Containers Manufacturing' },
{ value:'Hotels and Motels', label:'Hotels and Motels' },
{ value:'Automation Machinery Manufacturing', label:'Automation Machinery Manufacturing' },
{ value:'Wholesale Appliances, Electrical, and Electronics', label:'Wholesale Appliances, Electrical, and Electronics' },
{ value:'Government Relations Services', label:'Government Relations Services' },
{ value:'Bed-and-Breakfasts, Hostels, Homestays', label:'Bed-and-Breakfasts, Hostels, Homestays' },
{ value:'Horticulture', label:'Horticulture' },
{ value:'Wholesale Hardware, Plumbing, Heating Equipment', label:'Wholesale Hardware, Plumbing, Heating Equipment' },
{ value:'Wholesale Machinery', label:'Wholesale Machinery' },
{ value:'Caterers', label:'Caterers' },
{ value:'Mobile Food Services', label:'Mobile Food Services' },
{ value:'Renewable Energy Power Generation', label:'Renewable Energy Power Generation' },
{ value:'Bars, Taverns, and Nightclubs', label:'Bars, Taverns, and Nightclubs' },
{ value:'Renewable Energy Equipment Manufacturing', label:'Renewable Energy Equipment Manufacturing' },
{ value:'Engineering Services', label:'Engineering Services' },
{ value:'Services for Renewable Energy', label:'Services for Renewable Energy' },
{ value:'Digital Accessibility Services', label:'Digital Accessibility Services' },
{ value:'Accessible Hardware Manufacturing', label:'Accessible Hardware Manufacturing' },
{ value:'Accessible Architecture and Design', label:'Accessible Architecture and Design' },
{ value:'Robot Manufacturing', label:'Robot Manufacturing' },
{ value:'Robotics Engineering', label:'Robotics Engineering' },
{ value:'Repair and Maintenance', label:'Repair and Maintenance' },
{ value:'Surveying and Mapping Services', label:'Surveying and Mapping Services' },
{ value:'Vehicle Repair and Maintenance', label:'Vehicle Repair and Maintenance' },
{ value:'Retail Pharmacies', label:'Retail Pharmacies' },
{ value:'Climate Technology Product Manufacturing', label:'Climate Technology Product Manufacturing' },
{ value:'Climate Data and Analytics', label:'Climate Data and Analytics' },
{ value:'Alternative Fuel Vehicle Manufacturing', label:'Alternative Fuel Vehicle Manufacturing' },
{ value:'Wholesale Recyclable Materials', label:'Wholesale Recyclable Materials' },
{ value:'Smart Meter Manufacturing', label:'Smart Meter Manufacturing' },
{ value:'Fuel Cell Manufacturing', label:'Fuel Cell Manufacturing' },
{ value:'Wholesale Luxury Goods and Jewelry', label:'Wholesale Luxury Goods and Jewelry' },
{ value:'Regenerative Design', label:'Regenerative Design' },
{ value:'Wholesale Paper Products', label:'Wholesale Paper Products' },
{ value:'Electronic and Precision Equipment Maintenance', label:'Electronic and Precision Equipment Maintenance' },
{ value:'Wholesale Drugs and Sundries', label:'Wholesale Drugs and Sundries' },
{ value:'Wholesale Apparel and Sewing Supplies', label:'Wholesale Apparel and Sewing Supplies' },
{ value:'Commercial and Industrial Machinery Maintenance', label:'Commercial and Industrial Machinery Maintenance' },
{ value:'Farming, Ranching, Forestry', label:'Farming, Ranching, Forestry' },
{ value:'Reupholstery and Furniture Repair', label:'Reupholstery and Furniture Repair' },
{ value:'Wholesale Footwear', label:'Wholesale Footwear' },
{ value:'Wholesale Food and Beverage', label:'Wholesale Food and Beverage' },
{ value:'Footwear and Leather Goods Repair', label:'Footwear and Leather Goods Repair' },
{ value:'Personal and Laundry Services', label:'Personal and Laundry Services' },
{ value:'Personal Care Services', label:'Personal Care Services' },
{ value:'Laundry and Drycleaning Services', label:'Laundry and Drycleaning Services' },
{ value:'Wholesale Raw Farm Products', label:'Wholesale Raw Farm Products' },
{ value:'Wholesale Chemical and Allied Products', label:'Wholesale Chemical and Allied Products' },
{ value:'Pet Services', label:'Pet Services' },
{ value:'Wholesale Petroleum and Petroleum Products', label:'Wholesale Petroleum and Petroleum Products' },
{ value:'Wholesale Alcoholic Beverages', label:'Wholesale Alcoholic Beverages' },
{ value:'Ranching and Fisheries', label:'Ranching and Fisheries' },
{ value:'Internet Marketplace Platforms', label:'Internet Marketplace Platforms' },
{ value:'Retail Motor Vehicles', label:'Retail Motor Vehicles' },

        // Add more cities as needed
      ],
    },
    {
      id: "level",
      name: "Job Level",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Manager", label: "Manager" },
        { value: "Board Memebers and Owners", label: "Board Memebers and Owners" },
        { value: "Individual Contributor", label: "Individual Contributor" },
        { value: "VP Level", label: "VP Level" },
        { value: "Director", label: "Director" },
        { value: "C Level", label: "C Level" },
        { value: "Supervisor", label: "Supervisor" },

      ],
    },
    {
      id: "function",
      name: "Job Function",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Customer Service", label: "Customer Service" },
        { value: "Education", label: "Education" },
        { value: "Engineering", label: "Engineering" },
        { value: "Finance", label: "Finance" },
        { value: "Government", label: "Government" },
        { value: "Healthcare Services", label: "Healthcare Services" },
        { value: "Human Resources", label: "Human Resources" },
        { value: "IT", label: "IT" },
        { value: "Legal", label: "Legal" },
        { value: "Marketing", label: "Marketing" },
        { value: "Operations", label: "Operations" },
        { value: "Other", label: "Other" },
        { value: "Sales", label: "Sales" },

        // Add more cities as needed
      ],
    },
    
  ];
  
  export default filters;
  