// filters.js

const filters = [
    {
    id: "employee",
    name: "Employee",
    options: 
      [
        { value: "1-10 employees", label: "1-10 employees" },
        { value: "11-50 employees", label: "11-50 employees" },
        { value: "51-200 employees", label: "51-200 employees" },
        { value: "201-500 employees", label: "201-500 employees" },
        { value: "501-1,000 employees", label: "501-1,000 employees" },
        { value: "1,001-5,000 employees", label: "1,001-5,000 employees" },
        { value: "5,001-10,000 employees", label: "5,001-10,000 employees" },
        { value: "10,001+ employees", label: "10,001+ employees" },
      ],
    },
    {
      id: "industry",
      name: "Industry",
      options: [
        { value:'Advertising/Media/Publishing', label:'Advertising/Media/Publishing' },
{ value:'Aerospace and Aviation', label:'Aerospace and Aviation' },
{ value:'Agriculture and Forestry', label:'Agriculture and Forestry' },
{ value:'Banking/Accounting/Financial', label:'Banking/Accounting/Financial' },
{ value:'Business Services', label:'Business Services' },
{ value:'Computer and Technology', label:'Computer and Technology' },
{ value:'Education', label:'Education' },
{ value:'Engineering and Construction', label:'Engineering and Construction' },
{ value:'Entertainment/Travel/Hospitality', label:'Entertainment/Travel/Hospitality' },
{ value:'Food and Beverage', label:'Food and Beverage' },
{ value:'Government', label:'Government' },
{ value:'Healthcare', label:'Healthcare' },
{ value:'Legal Solutions', label:'Legal Solutions' },
{ value:'Manufacturing', label:'Manufacturing' },
{ value:'Non profit Organizations', label:'Non profit Organizations' },
{ value:'Oil, Gas and Mining', label:'Oil, Gas and Mining' },
{ value:'Other', label:'Other' },
{ value:'Professional services', label:'Professional services' },
{ value:'Public Relations', label:'Public Relations' },
{ value:'Real Estate', label:'Real Estate' },
{ value:'Renewables & Environment', label:'Renewables & Environment' },
{ value:'Research', label:'Research' },
{ value:'Retail', label:'Retail' },
{ value:'Telecommunications', label:'Telecommunications' },
{ value:'Transportation and Shipping', label:'Transportation and Shipping' },
{ value:'Utilities', label:'Utilities' },
{ value:'Wholesale', label:'Wholesale' },

      ]
    },    
    {
      id: "title",
      name: "Job Title",
      options: [
        
      ],
    },
    {
      id: "region",
      name: "Region",
      options: [
        { value: "Africa", label: "Africa" },
        { value: "Asia", label: "Asia" },
        { value: "Benelux", label: "Benelux" },
        { value: "DACH", label: "DACH" },
        { value: "Europe", label: "Europe" },
        { value: "MENA", label: "MENA" },
        { value: "Nordics", label: "Nordics" },
        { value: "North America", label: "North America" },
        { value: "Oceania", label: "Oceania" },
        { value: "South America", label: "South America" },

      ],
    },
    {
      id: "country",
      name: "Country",
      options: [
        { value: "Afghanistan", label: "Afghanistan" },
        { value: "Albania", label: "Albania" },
        { value: "Algeria", label: "Algeria" },
        { value: "Andorra", label: "Andorra" },
        { value: "Angola", label: "Angola" },
        { value: "Argentina", label: "Argentina" },
        { value: "Armenia", label: "Armenia" },
        { value: "Australia", label: "Australia" },
        { value: "Austria", label: "Austria" },
        { value: "Azerbaijan", label: "Azerbaijan" },
        { value: "Bahrain", label: "Bahrain" },
        { value: "Bangladesh", label: "Bangladesh" },
        { value: "Belarus", label: "Belarus" },
        { value: "Belgium", label: "Belgium" },
        { value: "Bolivia", label: "Bolivia" },
        { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
        { value: "Botswana", label: "Botswana" },
        { value: "Brazil", label: "Brazil" },
        { value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
        { value: "British Virgin Islands", label: "British Virgin Islands" },
        { value: "Brunei", label: "Brunei" },
        { value: "Bulgaria", label: "Bulgaria" },
        { value: "Cambodia", label: "Cambodia" },
        { value: "Cameroon", label: "Cameroon" },
        { value: "Canada", label: "Canada" },
        { value: "Cayman Islands", label: "Cayman Islands" },
        { value: "Chile", label: "Chile" },
        { value: "China", label: "China" },
        { value: "Colombia", label: "Colombia" },
        { value: "Costa Rica", label: "Costa Rica" },
        { value: "Cote Dlvoire", label: "Cote Dlvoire" },
        { value: "Croatia", label: "Croatia" },
        { value: "Cyprus", label: "Cyprus" },
        { value: "Czechia", label: "Czechia" },
        { value: "Denmark", label: "Denmark" },
        { value: "Dominican Republic", label: "Dominican Republic" },
        { value: "Ecuador", label: "Ecuador" },
        { value: "Egypt", label: "Egypt" },
        { value: "El Salvador", label: "El Salvador" },
        { value: "Estonia", label: "Estonia" },
        { value: "Ethiopia", label: "Ethiopia" },
        { value: "Fiji", label: "Fiji" },
        { value: "Finland", label: "Finland" },
        { value: "France", label: "France" },
        { value: "French Polynesia", label: "French Polynesia" },
        { value: "Georgia", label: "Georgia" },
        { value: "Germany", label: "Germany" },
        { value: "Ghana", label: "Ghana" },
        { value: "Greece", label: "Greece" },
        { value: "Guatemala", label: "Guatemala" },
        { value: "Honduras", label: "Honduras" },
        { value: "Hong Kong", label: "Hong Kong" },
        { value: "Hungary", label: "Hungary" },
        { value: "Iceland", label: "Iceland" },
        { value: "India", label: "India" },
        { value: "Indonesia", label: "Indonesia" },
        { value: "Iran", label: "Iran" },
        { value: "Iraq", label: "Iraq" },
        { value: "Ireland", label: "Ireland" },
        { value: "Israel", label: "Israel" },
        { value: "Italy", label: "Italy" },
        { value: "Ivory Coast", label: "Ivory Coast" },
        { value: "Jamaica", label: "Jamaica" },
        { value: "Japan", label: "Japan" },
        { value: "Jordan", label: "Jordan" },
        { value: "Kazakhstan", label: "Kazakhstan" },
        { value: "Kenya", label: "Kenya" },
        { value: "Kuwait", label: "Kuwait" },
        { value: "Laos", label: "Laos" },
        { value: "Latvia", label: "Latvia" },
        { value: "Lebanon", label: "Lebanon" },
        { value: "Libya", label: "Libya" },
        { value: "Liechtenstein", label: "Liechtenstein" },
        { value: "Lithuania", label: "Lithuania" },
        { value: "Luxembourg", label: "Luxembourg" },
        { value: "Macau", label: "Macau" },
        { value: "Malaysia", label: "Malaysia" },
        { value: "Malta", label: "Malta" },
        { value: "Mauritius", label: "Mauritius" },
        { value: "Mexico", label: "Mexico" },
        { value: "Monaco", label: "Monaco" },
        { value: "Morocco", label: "Morocco" },
        { value: "Myanmar", label: "Myanmar" },
        { value: "Namibia", label: "Namibia" },
        { value: "Nepal", label: "Nepal" },
        { value: "Netherlands", label: "Netherlands" },
        { value: "New Zealand", label: "New Zealand" },
        { value: "Nicaragua", label: "Nicaragua" },
        { value: "Nigeria", label: "Nigeria" },
        { value: "North Korea", label: "North Korea" },
        { value: "North Macedonia", label: "North Macedonia" },
        { value: "Norway", label: "Norway" },
        { value: "Oman", label: "Oman" },
        { value: "Pakistan", label: "Pakistan" },
        { value: "Panama", label: "Panama" },
        { value: "Papua New Guinea", label: "Papua New Guinea" },
        { value: "Paraguay", label: "Paraguay" },
        { value: "Peru", label: "Peru" },
        { value: "Philippines", label: "Philippines" },
        { value: "Poland", label: "Poland" },
        { value: "Portugal", label: "Portugal" },
        { value: "Puerto Rico", label: "Puerto Rico" },
        { value: "Qatar", label: "Qatar" },
        { value: "Romania", label: "Romania" },
        { value: "Russia", label: "Russia" },
        { value: "Rwanda", label: "Rwanda" },
        { value: "Saudi Arabia", label: "Saudi Arabia" },
        { value: "Senegal", label: "Senegal" },
        { value: "Serbia", label: "Serbia" },
        { value: "Seychelles", label: "Seychelles" },
        { value: "Singapore", label: "Singapore" },
        { value: "Slovakia", label: "Slovakia" },
        { value: "Slovenia", label: "Slovenia" },
        { value: "South Africa", label: "South Africa" },
        { value: "South Korea", label: "South Korea" },
        { value: "Spain", label: "Spain" },
        { value: "Sri Lanka", label: "Sri Lanka" },
        { value: "Sudan", label: "Sudan" },
        { value: "Sweden", label: "Sweden" },
        { value: "Switzerland", label: "Switzerland" },
        { value: "Syria", label: "Syria" },
        { value: "Taiwan", label: "Taiwan" },
        { value: "Tanzania", label: "Tanzania" },
        { value: "Thailand", label: "Thailand" },
        { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
        { value: "Tunisia", label: "Tunisia" },
        { value: "Turkey", label: "Turkey" },
        { value: "Turkmenistan", label: "Turkmenistan" },
        { value: "Uganda", label: "Uganda" },
        { value: "Ukraine", label: "Ukraine" },
        { value: "United Arab Emirates", label: "United Arab Emirates" },
        { value: "United Kingdom", label: "United Kingdom" },
        { value: "United States", label: "United States" },
        { value: "Uruguay", label: "Uruguay" },
        { value: "Venezuela", label: "Venezuela" },
        { value: "Vietnam", label: "Vietnam" },
        { value: "Yemen", label: "Yemen" },
        { value: "Zambia", label: "Zambia" },
        { value: "Zimbabwe", label: "Zimbabwe" }
      ],
    },
    {
      id: "state",
      name: "State",
      options: [
        // States could be dynamically loaded based on the selected country
        { value: "California", label: "California" },
        { value: "New York", label: "New York" },
        // Add more states as needed
      ],
    },
    {
      id: "city",
      name: "City",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Los Angeles", label: "Los Angeles" },
        { value: "New York City", label: "New York City" },
        // Add more cities as needed
      ],
    },
    {
      id: "sub_industry",
      name: "sub_industry",
      options: [
        { value:'Advertising Services', label:'Advertising Services' },
        { value:'Blogs', label:'Blogs' },
        { value:'Book and Periodical Publishing', label:'Book and Periodical Publishing' },
        { value:'Book Publishing', label:'Book Publishing' },
        { value:'Broadcast Media Production and Distribution', label:'Broadcast Media Production and Distribution' },
        { value:'Media and Telecommunications', label:'Media and Telecommunications' },
        { value:'Media Production', label:'Media Production' },
        { value:'Periodical Publishing', label:'Periodical Publishing' },
        { value:'Sheet Music Publishing', label:'Sheet Music Publishing' },
        { value:'Internet Publishing', label:'Internet Publishing' },
        { value:'Newspaper Publishing', label:'Newspaper Publishing' },
        { value:'Online Audio and Video Media', label:'Online Audio and Video Media' },
        { value:'Aviation and Aerospace Component Manufacturing', label:'Aviation and Aerospace Component Manufacturing' },
        { value:'Airlines and Aviation', label:'Airlines and Aviation' },
        { value:'Farming', label:'Farming' },
        { value:'Farming, Ranching, Forestry', label:'Farming, Ranching, Forestry' },
        { value:'Forestry and Logging', label:'Forestry and Logging' },
        { value:'Ranching and Fisheries', label:'Ranching and Fisheries' },
        { value:'Fisheries', label:'Fisheries' },
        { value:'Horticulture', label:'Horticulture' },
        { value:'Ranching', label:'Ranching' },
        { value:'Accounting', label:'Accounting' },
        { value:'Banking', label:'Banking' },
        { value:'Claims Adjusting, Actuarial Services', label:'Claims Adjusting, Actuarial Services' },
        { value:'Collection Agencies', label:'Collection Agencies' },
        { value:'Credit Intermediation', label:'Credit Intermediation' },
        { value:'Financial Services', label:'Financial Services' },
        { value:'Insurance', label:'Insurance' },
        { value:'Insurance Agencies and Brokerages', label:'Insurance Agencies and Brokerages' },
        { value:'Insurance and Employee Benefit Funds', label:'Insurance and Employee Benefit Funds' },
        { value:'Insurance Carriers', label:'Insurance Carriers' },
        { value:'Investment Advice', label:'Investment Advice' },
        { value:'Investment Banking', label:'Investment Banking' },
        { value:'Investment Management', label:'Investment Management' },
        { value:'Capital Markets', label:'Capital Markets' },
        { value:'Venture Capital and Private Equity Principals', label:'Venture Capital and Private Equity Principals' },
        { value:'Administrative and Support Services', label:'Administrative and Support Services' },
        { value:'Ambulance Services', label:'Ambulance Services' },
        { value:'Blockchain Services', label:'Blockchain Services' },
        { value:'Business Consulting and Services', label:'Business Consulting and Services' },
        { value:'Child Day Care Services', label:'Child Day Care Services' },
        { value:'Consumer Services', label:'Consumer Services' },
        { value:'Design Services', label:'Design Services' },
        { value:'Emergency and Relief Services', label:'Emergency and Relief Services' },
        { value:'Equipment Rental Services', label:'Equipment Rental Services' },
        { value:'Events Services', label:'Events Services' },
        { value:'Executive Offices', label:'Executive Offices' },
        { value:'Executive Search Services', label:'Executive Search Services' },
        { value:'Facilities Services', label:'Facilities Services' },
        { value:'Graphic Design', label:'Graphic Design' },
        { value:'Health and Human Services', label:'Health and Human Services' },
        { value:'Household Services', label:'Household Services' },
        { value:'Human Resources Services', label:'Human Resources Services' },
        { value:'Individual and Family Services', label:'Individual and Family Services' },
        { value:'international trade and development', label:'international trade and development' },
        { value:'Interurban and Rural Bus Services', label:'Interurban and Rural Bus Services' },
        { value:'Janitorial Services', label:'Janitorial Services' },
        { value:'Landscaping Services', label:'Landscaping Services' },
        { value:'Laundry and Drycleaning Services', label:'Laundry and Drycleaning Services' },
        { value:'Market Research', label:'Market Research' },
        { value:'Marketing Services', label:'Marketing Services' },
        { value:'Outsourcing and Offshoring Consulting', label:'Outsourcing and Offshoring Consulting' },
        { value:'Personal and Laundry Services', label:'Personal and Laundry Services' },
        { value:'Personal Care Services', label:'Personal Care Services' },
        { value:'Pet Services', label:'Pet Services' },
        { value:'Photography', label:'Photography' },
        { value:'Postal Services', label:'Postal Services' },
        { value:'Printing Services', label:'Printing Services' },
        { value:'Professional Services', label:'Professional Services' },
        { value:'Professional Training and Coaching', label:'Professional Training and Coaching' },
        { value:'School and Employee Bus Services', label:'School and Employee Bus Services' },
        { value:'security and investigations', label:'security and investigations' },
        { value:'Security Guards and Patrol Services', label:'Security Guards and Patrol Services' },
        { value:'Security Systems Services', label:'Security Systems Services' },
        { value:'Services for the Elderly and Disabled', label:'Services for the Elderly and Disabled' },
        { value:'Staffing and Recruiting', label:'Staffing and Recruiting' },
        { value:'Strategic Management Services', label:'Strategic Management Services' },
        { value:'Taxi and Limousine Services', label:'Taxi and Limousine Services' },
        { value:'Temporary Help Services', label:'Temporary Help Services' },
        { value:'Translation and Localization', label:'Translation and Localization' },
        { value:'Urban Transit Services', label:'Urban Transit Services' },
        { value:'Vocational Rehabilitation Services', label:'Vocational Rehabilitation Services' },
        { value:'Warehousing and Storage', label:'Warehousing and Storage' },
        { value:'Water, Waste, Steam, and Air Conditioning Services', label:'Water, Waste, Steam, and Air Conditioning Services' },
        { value:'Wellness and Fitness Services', label:'Wellness and Fitness Services' },
        { value:'Wireless Services', label:'Wireless Services' },
        { value:'Writing and Editing', label:'Writing and Editing' },
        { value:'Commercial and Industrial Equipment Rental', label:'Commercial and Industrial Equipment Rental' },
        { value:'Commercial and Industrial Machinery Maintenance', label:'Commercial and Industrial Machinery Maintenance' },
        { value:'Consumer Goods Rental', label:'Consumer Goods Rental' },
        { value:'Economic Programs', label:'Economic Programs' },
        { value:'Electronic and Precision Equipment Maintenance', label:'Electronic and Precision Equipment Maintenance' },
        { value:'Engineering Services', label:'Engineering Services' },
        { value:'Holding Companies', label:'Holding Companies' },
        { value:'Housing Programs', label:'Housing Programs' },
        { value:'Operations Consulting', label:'Operations Consulting' },
        { value:'Physical, Occupational and Speech Therapists', label:'Physical, Occupational and Speech Therapists' },
        { value:'Recreational Facilities', label:'Recreational Facilities' },
        { value:'Repair and Maintenance', label:'Repair and Maintenance' },
        { value:'Skiing Facilities', label:'Skiing Facilities' },
        { value:'Specialty Trade Contractors', label:'Specialty Trade Contractors' },
        { value:'Surveying and Mapping Services', label:'Surveying and Mapping Services' },
        { value:'Vehicle Repair and Maintenance', label:'Vehicle Repair and Maintenance' },
        { value:'Computer and Network Security', label:'Computer and Network Security' },
        { value:'Computer Games', label:'Computer Games' },
        { value:'Computer Networking Products', label:'Computer Networking Products' },
        { value:'Data Security Software Products', label:'Data Security Software Products' },
        { value:'Desktop Computing Software Products', label:'Desktop Computing Software Products' },
        { value:'Embedded Software Products', label:'Embedded Software Products' },
        { value:'Information Services', label:'Information Services' },
        { value:'IT Services and IT Consulting', label:'IT Services and IT Consulting' },
        { value:'IT System Custom Software Development', label:'IT System Custom Software Development' },
        { value:'IT System Data Services', label:'IT System Data Services' },
        { value:'IT System Design Services', label:'IT System Design Services' },
        { value:'IT System Installation and Disposal', label:'IT System Installation and Disposal' },
        { value:'IT System Operations and Maintenance', label:'IT System Operations and Maintenance' },
        { value:'IT System Testing and Evaluation', label:'IT System Testing and Evaluation' },
        { value:'IT System Training and Support', label:'IT System Training and Support' },
        { value:'Mobile Computing Software Products', label:'Mobile Computing Software Products' },
        { value:'Software Development', label:'Software Development' },
        { value:'Technology, Information and Internet', label:'Technology, Information and Internet' },
        { value:'Technology, Information and Media', label:'Technology, Information and Media' },
        { value:'Business Intelligence Platforms', label:'Business Intelligence Platforms' },
        { value:'Cable and Satellite Programming', label:'Cable and Satellite Programming' },
        { value:'Data Infrastructure and Analytics', label:'Data Infrastructure and Analytics' },
        { value:'Internet Marketplace Platforms', label:'Internet Marketplace Platforms' },
        { value:'Robotics Engineering', label:'Robotics Engineering' },
        { value:'Social Networking Platforms', label:'Social Networking Platforms' },
        { value:'Education', label:'Education' },
        { value:'Education Administration Programs', label:'Education Administration Programs' },
        { value:'Higher Education', label:'Higher Education' },
        { value:'K-12 Schools', label:'K-12 Schools' },
        { value:'Primary and Secondary Education', label:'Primary and Secondary Education' },
        { value:'E-Learning Providers', label:'E-Learning Providers' },
        { value:'Language Schools', label:'Language Schools' },
        { value:'Architecture and Planning', label:'Architecture and Planning' },
        { value:'Building Construction', label:'Building Construction' },
        { value:'Civil Engineering', label:'Civil Engineering' },
        { value:'Construction', label:'Construction' },
        { value:'Highway, Street, and Bridge Construction', label:'Highway, Street, and Bridge Construction' },
        { value:'Nonresidential Building Construction', label:'Nonresidential Building Construction' },
        { value:'Residential Building Construction', label:'Residential Building Construction' },
        { value:'Utility System Construction', label:'Utility System Construction' },
        { value:'Accessible Architecture and Design', label:'Accessible Architecture and Design' },
        { value:'Building Equipment Contractors', label:'Building Equipment Contractors' },
        { value:'Building Finishing Contractors', label:'Building Finishing Contractors' },
        { value:'Interior Design', label:'Interior Design' },
        { value:'Accommodation and Food Services', label:'Accommodation and Food Services' },
        { value:'Amusement Parks and Arcades', label:'Amusement Parks and Arcades' },
        { value:'Animation and Post-production', label:'Animation and Post-production' },
        { value:'Bars, Taverns, and Nightclubs', label:'Bars, Taverns, and Nightclubs' },
        { value:'Bed-and-Breakfasts, Hostels, Homestays', label:'Bed-and-Breakfasts, Hostels, Homestays' },
        { value:'Caterers', label:'Caterers' },
        { value:'Circuses and Magic Shows', label:'Circuses and Magic Shows' },
        { value:'Dance Companies', label:'Dance Companies' },
        { value:'Entertainment Providers', label:'Entertainment Providers' },
        { value:'Fine Arts Schools', label:'Fine Arts Schools' },
        { value:'Gambling Facilities and Casinos', label:'Gambling Facilities and Casinos' },
        { value:'Hospitality', label:'Hospitality' },
        { value:'Hotels and Motels', label:'Hotels and Motels' },
        { value:'Internet News', label:'Internet News' },
        { value:'Mobile Gaming Apps', label:'Mobile Gaming Apps' },
        { value:'Movies and Sound Recording', label:'Movies and Sound Recording' },
        { value:'Movies, Videos, and Sound', label:'Movies, Videos, and Sound' },
        { value:'Performing Arts', label:'Performing Arts' },
        { value:'Performing Arts and Spectator Sports', label:'Performing Arts and Spectator Sports' },
        { value:'Restaurants', label:'Restaurants' },
        { value:'Travel Arrangements', label:'Travel Arrangements' },
        { value:'Artists and Writers', label:'Artists and Writers' },
        { value:'Golf Courses and Country Clubs', label:'Golf Courses and Country Clubs' },
        { value:'Musicians', label:'Musicians' },
        { value:'Radio and Television Broadcasting', label:'Radio and Television Broadcasting' },
        { value:'Spectator Sports', label:'Spectator Sports' },
        { value:'Sports and Recreation Instruction', label:'Sports and Recreation Instruction' },
        { value:'Sports Teams and Clubs', label:'Sports Teams and Clubs' },
        { value:'Breweries', label:'Breweries' },
        { value:'Food and Beverage Manufacturing', label:'Food and Beverage Manufacturing' },
        { value:'Food and Beverage Services', label:'Food and Beverage Services' },
        { value:'Mobile Food Services', label:'Mobile Food Services' },
        { value:'Seafood Product Manufacturing', label:'Seafood Product Manufacturing' },
        { value:'Wineries', label:'Wineries' },
        { value:'Government Relations Services', label:'Government Relations Services' },
        { value:'Administration of Justice', label:'Administration of Justice' },
        { value:'Armed Forces', label:'Armed Forces' },
        { value:'Government Administration', label:'Government Administration' },
        { value:'Legislative Offices', label:'Legislative Offices' },
        { value:'Military and International Affairs', label:'Military and International Affairs' },
        { value:'Alternative Medicine', label:'Alternative Medicine' },
        { value:'Home Health Care Services', label:'Home Health Care Services' },
        { value:'Hospitals', label:'Hospitals' },
        { value:'Hospitals and Health Care', label:'Hospitals and Health Care' },
        { value:'Medical and Diagnostic Laboratories', label:'Medical and Diagnostic Laboratories' },
        { value:'Medical Practices', label:'Medical Practices' },
        { value:'Mental Health Care', label:'Mental Health Care' },
        { value:'Veterinary Services', label:'Veterinary Services' },
        { value:'Dentists', label:'Dentists' },
        { value:'Nursing Homes and Residential Care Facilities', label:'Nursing Homes and Residential Care Facilities' },
        { value:'Optometrists', label:'Optometrists' },
        { value:'Alternative Dispute Resolution', label:'Alternative Dispute Resolution' },
        { value:'Courts of Law', label:'Courts of Law' },
        { value:'Law Enforcement', label:'Law Enforcement' },
        { value:'Law Practice', label:'Law Practice' },
        { value:'Legal Services', label:'Legal Services' },
        { value:'Abrasives and Nonmetallic Minerals Manufacturing', label:'Abrasives and Nonmetallic Minerals Manufacturing' },
        { value:'Agricultural Chemical Manufacturing', label:'Agricultural Chemical Manufacturing' },
        { value:'Agriculture, Construction, Mining Machinery Manufacturing', label:'Agriculture, Construction, Mining Machinery Manufacturing' },
        { value:'Animal Feed Manufacturing', label:'Animal Feed Manufacturing' },
        { value:'Apparel Manufacturing', label:'Apparel Manufacturing' },
        { value:'Appliances, Electrical, and Electronics Manufacturing', label:'Appliances, Electrical, and Electronics Manufacturing' },
        { value:'Architectural and Structural Metal Manufacturing', label:'Architectural and Structural Metal Manufacturing' },
        { value:'Artificial Rubber and Synthetic Fiber Manufacturing', label:'Artificial Rubber and Synthetic Fiber Manufacturing' },
        { value:'Audio and Video Equipment Manufacturing', label:'Audio and Video Equipment Manufacturing' },
        { value:'Automation Machinery Manufacturing', label:'Automation Machinery Manufacturing' },
        { value:'Baked Goods Manufacturing', label:'Baked Goods Manufacturing' },
        { value:'Beverage Manufacturing', label:'Beverage Manufacturing' },
        { value:'Boilers, Tanks, and Shipping Container Manufacturing', label:'Boilers, Tanks, and Shipping Container Manufacturing' },
        { value:'Chemical Manufacturing', label:'Chemical Manufacturing' },
        { value:'Chemical Raw Materials Manufacturing', label:'Chemical Raw Materials Manufacturing' },
        { value:'Clay and Refractory Products Manufacturing', label:'Clay and Refractory Products Manufacturing' },
        { value:'Commercial and Service Industry Machinery Manufacturing', label:'Commercial and Service Industry Machinery Manufacturing' },
        { value:'Communications Equipment Manufacturing', label:'Communications Equipment Manufacturing' },
        { value:'Computer Hardware Manufacturing', label:'Computer Hardware Manufacturing' },
        { value:'Computers and Electronics Manufacturing', label:'Computers and Electronics Manufacturing' },
        { value:'Construction Hardware Manufacturing', label:'Construction Hardware Manufacturing' },
        { value:'Cutlery and Handtool Manufacturing', label:'Cutlery and Handtool Manufacturing' },
        { value:'Dairy Product Manufacturing', label:'Dairy Product Manufacturing' },
        { value:'Defense and Space Manufacturing', label:'Defense and Space Manufacturing' },
        { value:'Electric Lighting Equipment Manufacturing', label:'Electric Lighting Equipment Manufacturing' },
        { value:'Electrical Equipment Manufacturing', label:'Electrical Equipment Manufacturing' },
        { value:'Engines and Power Transmission Equipment Manufacturing', label:'Engines and Power Transmission Equipment Manufacturing' },
        { value:'Fashion Accessories Manufacturing', label:'Fashion Accessories Manufacturing' },
        { value:'Footwear Manufacturing', label:'Footwear Manufacturing' },
        { value:'Fruit and Vegetable Preserves Manufacturing', label:'Fruit and Vegetable Preserves Manufacturing' },
        { value:'Furniture and Home Furnishings Manufacturing', label:'Furniture and Home Furnishings Manufacturing' },
        { value:'Glass Product Manufacturing', label:'Glass Product Manufacturing' },
        { value:'Glass, Ceramics and Concrete Manufacturing', label:'Glass, Ceramics and Concrete Manufacturing' },
        { value:'Household and Institutional Furniture Manufacturing', label:'Household and Institutional Furniture Manufacturing' },
        { value:'Household Appliance Manufacturing', label:'Household Appliance Manufacturing' },
        { value:'HVAC and Refrigeration Equipment Manufacturing', label:'HVAC and Refrigeration Equipment Manufacturing' },
        { value:'Industrial Machinery Manufacturing', label:'Industrial Machinery Manufacturing' },
        { value:'Leather Product Manufacturing', label:'Leather Product Manufacturing' },
        { value:'Lime and Gypsum Products Manufacturing', label:'Lime and Gypsum Products Manufacturing' },
        { value:'Machinery Manufacturing', label:'Machinery Manufacturing' },
        { value:'Magnetic and Optical Media Manufacturing', label:'Magnetic and Optical Media Manufacturing' },
        { value:'Manufacturing', label:'Manufacturing' },
        { value:'Mattress and Blinds Manufacturing', label:'Mattress and Blinds Manufacturing' },
        { value:'Measuring and Control Instrument Manufacturing', label:'Measuring and Control Instrument Manufacturing' },
        { value:'Meat Products Manufacturing', label:'Meat Products Manufacturing' },
        { value:'Medical Equipment Manufacturing', label:'Medical Equipment Manufacturing' },
        { value:'Metal Valve, Ball, and Roller Manufacturing', label:'Metal Valve, Ball, and Roller Manufacturing' },
        { value:'Metalworking Machinery Manufacturing', label:'Metalworking Machinery Manufacturing' },
        { value:'Motor Vehicle Manufacturing', label:'Motor Vehicle Manufacturing' },
        { value:'Motor Vehicle Parts Manufacturing', label:'Motor Vehicle Parts Manufacturing' },
        { value:'Office Furniture and Fixtures Manufacturing', label:'Office Furniture and Fixtures Manufacturing' },
        { value:'Packaging and Containers Manufacturing', label:'Packaging and Containers Manufacturing' },
        { value:'Paint, Coating, and Adhesive Manufacturing', label:'Paint, Coating, and Adhesive Manufacturing' },
        { value:'Paper and Forest Product Manufacturing', label:'Paper and Forest Product Manufacturing' },
        { value:'Personal Care Product Manufacturing', label:'Personal Care Product Manufacturing' },
        { value:'Pharmaceutical Manufacturing', label:'Pharmaceutical Manufacturing' },
        { value:'Plastics and Rubber Product Manufacturing', label:'Plastics and Rubber Product Manufacturing' },
        { value:'Plastics Manufacturing', label:'Plastics Manufacturing' },
        { value:'Primary Metal Manufacturing', label:'Primary Metal Manufacturing' },
        { value:'Railroad Equipment Manufacturing', label:'Railroad Equipment Manufacturing' },
        { value:'Rubber Products Manufacturing', label:'Rubber Products Manufacturing' },
        { value:'Semiconductor Manufacturing', label:'Semiconductor Manufacturing' },
        { value:'Shipbuilding', label:'Shipbuilding' },
        { value:'Soap and Cleaning Product Manufacturing', label:'Soap and Cleaning Product Manufacturing' },
        { value:'Sporting Goods Manufacturing', label:'Sporting Goods Manufacturing' },
        { value:'Spring and Wire Product Manufacturing', label:'Spring and Wire Product Manufacturing' },
        { value:'Sugar and Confectionery Product Manufacturing', label:'Sugar and Confectionery Product Manufacturing' },
        { value:'Textile Manufacturing', label:'Textile Manufacturing' },
        { value:'Tobacco Manufacturing', label:'Tobacco Manufacturing' },
        { value:'Transportation Equipment Manufacturing', label:'Transportation Equipment Manufacturing' },
        { value:'Turned Products and Fastener Manufacturing', label:'Turned Products and Fastener Manufacturing' },
        { value:`Women's Handbag Manufacturing`, label:`Women's Handbag Manufacturing` },
        { value:'Wood Product Manufacturing', label:'Wood Product Manufacturing' },
        { value:'Climate Technology Product Manufacturing', label:'Climate Technology Product Manufacturing' },
        { value:'Fuel Cell Manufacturing', label:'Fuel Cell Manufacturing' },
        { value:'Smart Meter Manufacturing', label:'Smart Meter Manufacturing' },
        { value:'Civic and Social Organizations', label:'Civic and Social Organizations' },
        { value:'Fundraising', label:'Fundraising' },
        { value:'Funds and Trusts', label:'Funds and Trusts' },
        { value:'Historical Sites', label:'Historical Sites' },
        { value:'Libraries', label:'Libraries' },
        { value:'Museums', label:'Museums' },
        { value:'Museums, Historical Sites, and Zoos', label:'Museums, Historical Sites, and Zoos' },
        { value:'Pension Funds', label:'Pension Funds' },
        { value:'Philanthropic Fundraising Services', label:'Philanthropic Fundraising Services' },
        { value:'Political Organizations', label:'Political Organizations' },
        { value:'Religious Institutions', label:'Religious Institutions' },
        { value:'Think Tanks', label:'Think Tanks' },
        { value:'Non-profit Organizations', label:'Non-profit Organizations' },
        { value:'Coal Mining', label:'Coal Mining' },
        { value:'Metal Ore Mining', label:'Metal Ore Mining' },
        { value:'Mining', label:'Mining' },
        { value:'Natural Gas Extraction', label:'Natural Gas Extraction' },
        { value:'Nonmetallic Mineral Mining', label:'Nonmetallic Mineral Mining' },
        { value:'Oil and Coal Product Manufacturing', label:'Oil and Coal Product Manufacturing' },
        { value:'Oil and Gas', label:'Oil and Gas' },
        { value:'Oil Extraction', label:'Oil Extraction' },
        { value:'Oil, Gas, and Mining', label:'Oil, Gas, and Mining' },
        { value:'Other', label:'Other' },
        { value:'Community Development and Urban Planning', label:'Community Development and Urban Planning' },
        { value:'Flight Training', label:'Flight Training' },
        { value:'Housing and Community Development', label:'Housing and Community Development' },
        { value:'Public Health', label:'Public Health' },
        { value:'Technical and Vocational Training', label:'Technical and Vocational Training' },
        { value:'Industry Associations', label:'Industry Associations' },
        { value:'International Affairs', label:'International Affairs' },
        { value:'Metal Treatments', label:'Metal Treatments' },
        { value:'Professional Organizations', label:'Professional Organizations' },
        { value:'Community Services', label:'Community Services' },
        { value:'Public Assistance Programs', label:'Public Assistance Programs' },
        { value:'Public Policy Offices', label:'Public Policy Offices' },
        { value:'Public Relations and Communications Services', label:'Public Relations and Communications Services' },
        { value:'Public Safety', label:'Public Safety' },
        { value:'Air, Water, and Waste Program Management', label:'Air, Water, and Waste Program Management' },
        { value:'Conservation Programs', label:'Conservation Programs' },
        { value:'Fire Protection', label:'Fire Protection' },
        { value:'Natural Gas Distribution', label:'Natural Gas Distribution' },
        { value:'Subdivision of Land', label:'Subdivision of Land' },
        { value:'Waste Collection', label:'Waste Collection' },
        { value:'Waste Treatment and Disposal', label:'Waste Treatment and Disposal' },
        { value:'Water Supply and Irrigation Systems', label:'Water Supply and Irrigation Systems' },
        { value:'Leasing Non-residential Real Estate', label:'Leasing Non-residential Real Estate' },
        { value:'Leasing Residential Real Estate', label:'Leasing Residential Real Estate' },
        { value:'Real Estate', label:'Real Estate' },
        { value:'Real Estate Agents and Brokers', label:'Real Estate Agents and Brokers' },
        { value:'Real Estate and Equipment Rental Services', label:'Real Estate and Equipment Rental Services' },
        { value:'Environmental Services', label:'Environmental Services' },
        { value:'Biomass Electric Power Generation', label:'Biomass Electric Power Generation' },
        { value:'Environmental Quality Programs', label:'Environmental Quality Programs' },
        { value:'Geothermal Electric Power Generation', label:'Geothermal Electric Power Generation' },
        { value:'Hydroelectric Power Generation', label:'Hydroelectric Power Generation' },
        { value:'Renewable Energy Equipment Manufacturing', label:'Renewable Energy Equipment Manufacturing' },
        { value:'Renewable Energy Power Generation', label:'Renewable Energy Power Generation' },
        { value:'Services for Renewable Energy', label:'Services for Renewable Energy' },
        { value:'Solar Electric Power Generation', label:'Solar Electric Power Generation' },
        { value:'Wind Electric Power Generation', label:'Wind Electric Power Generation' },
        { value:'Biotechnology Research', label:'Biotechnology Research' },
        { value:'Nanotechnology Research', label:'Nanotechnology Research' },
        { value:'Research Services', label:'Research Services' },
        { value:'Space Research and Technology', label:'Space Research and Technology' },
        { value:'Food and Beverage Retail', label:'Food and Beverage Retail' },
        { value:'Online and Mail Order Retail', label:'Online and Mail Order Retail' },
        { value:'Retail', label:'Retail' },
        { value:'Retail Apparel and Fashion', label:'Retail Apparel and Fashion' },
        { value:'Retail Appliances, Electrical, and Electronic Equipment', label:'Retail Appliances, Electrical, and Electronic Equipment' },
        { value:'Retail Art Dealers', label:'Retail Art Dealers' },
        { value:'Retail Art Supplies', label:'Retail Art Supplies' },
        { value:'Retail Books and Printed News', label:'Retail Books and Printed News' },
        { value:'Retail Building Materials and Garden Equipment', label:'Retail Building Materials and Garden Equipment' },
        { value:'Retail Florists', label:'Retail Florists' },
        { value:'Retail Furniture and Home Furnishings', label:'Retail Furniture and Home Furnishings' },
        { value:'Retail Gasoline', label:'Retail Gasoline' },
        { value:'Retail Groceries', label:'Retail Groceries' },
        { value:'Retail Health and Personal Care Products', label:'Retail Health and Personal Care Products' },
        { value:'Retail Luxury Goods and Jewelry', label:'Retail Luxury Goods and Jewelry' },
        { value:'Retail Motor Vehicles', label:'Retail Motor Vehicles' },
        { value:'Retail Musical Instruments', label:'Retail Musical Instruments' },
        { value:'Retail Office Equipment', label:'Retail Office Equipment' },
        { value:'Retail Office Supplies and Gifts', label:'Retail Office Supplies and Gifts' },
        { value:'Retail Recyclable Materials & Used Merchandise', label:'Retail Recyclable Materials & Used Merchandise' },
        { value:'Fabricated Metal Products', label:'Fabricated Metal Products' },
        { value:'Retail Pharmacies', label:'Retail Pharmacies' },
        { value:'Satellite Telecommunications', label:'Satellite Telecommunications' },
        { value:'Telecommunications', label:'Telecommunications' },
        { value:'Telecommunications Carriers', label:'Telecommunications Carriers' },
        { value:'Telephone Call Centers', label:'Telephone Call Centers' },
        { value:'Freight and Package Transportation', label:'Freight and Package Transportation' },
        { value:'Ground Passenger Transportation', label:'Ground Passenger Transportation' },
        { value:'Maritime Transportation', label:'Maritime Transportation' },
        { value:'Pipeline Transportation', label:'Pipeline Transportation' },
        { value:'Rail Transportation', label:'Rail Transportation' },
        { value:'Shuttles and Special Needs Transportation Services', label:'Shuttles and Special Needs Transportation Services' },
        { value:'Sightseeing Transportation', label:'Sightseeing Transportation' },
        { value:'Transportation Programs', label:'Transportation Programs' },
        { value:'Transportation, Logistics, Supply Chain and Storage', label:'Transportation, Logistics, Supply Chain and Storage' },
        { value:'Truck Transportation', label:'Truck Transportation' },
        { value:'Utilities', label:'Utilities' },
        { value:'Utilities Administration', label:'Utilities Administration' },
        { value:'Electric Power Generation', label:'Electric Power Generation' },
        { value:'Electric Power Transmission, Control, and Distribution', label:'Electric Power Transmission, Control, and Distribution' },
        { value:'Nuclear Electric Power Generation', label:'Nuclear Electric Power Generation' },
        { value:'Wholesale', label:'Wholesale' },
        { value:'Wholesale Alcoholic Beverages', label:'Wholesale Alcoholic Beverages' },
        { value:'Wholesale Apparel and Sewing Supplies', label:'Wholesale Apparel and Sewing Supplies' },
        { value:'Wholesale Appliances, Electrical, and Electronics', label:'Wholesale Appliances, Electrical, and Electronics' },
        { value:'Wholesale Building Materials', label:'Wholesale Building Materials' },
        { value:'Wholesale Chemical and Allied Products', label:'Wholesale Chemical and Allied Products' },
        { value:'Wholesale Computer Equipment', label:'Wholesale Computer Equipment' },
        { value:'Wholesale Drugs and Sundries', label:'Wholesale Drugs and Sundries' },
        { value:'Wholesale Food and Beverage', label:'Wholesale Food and Beverage' },
        { value:'Wholesale Footwear', label:'Wholesale Footwear' },
        { value:'Wholesale Furniture and Home Furnishings', label:'Wholesale Furniture and Home Furnishings' },
        { value:'Wholesale Hardware, Plumbing, Heating Equipment', label:'Wholesale Hardware, Plumbing, Heating Equipment' },
        { value:'Wholesale Import and Export', label:'Wholesale Import and Export' },
        { value:'Wholesale Luxury Goods and Jewelry', label:'Wholesale Luxury Goods and Jewelry' },
        { value:'Wholesale Machinery', label:'Wholesale Machinery' },
        { value:'Wholesale Metals and Minerals', label:'Wholesale Metals and Minerals' },
        { value:'Wholesale Motor Vehicles and Parts', label:'Wholesale Motor Vehicles and Parts' },
        { value:'Wholesale Paper Products', label:'Wholesale Paper Products' },
        { value:'Wholesale Petroleum and Petroleum Products', label:'Wholesale Petroleum and Petroleum Products' },
        { value:'Wholesale Photography Equipment and Supplies', label:'Wholesale Photography Equipment and Supplies' },
        { value:'Wholesale Raw Farm Products', label:'Wholesale Raw Farm Products' },
        { value:'Wholesale Recyclable Materials', label:'Wholesale Recyclable Materials' },
        

        // Add more cities as needed
      ],
    },
    {
      id: "level",
      name: "Job Level",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Manager", label: "Manager" },
        { value: "Board Memebers and Owners", label: "Board Memebers and Owners" },
        { value: "Individual Contributor", label: "Individual Contributor" },
        { value: "Vice President", label: "Vice President" },
        { value: "Director", label: "Director" },
        { value: "C Level", label: "C Level" },
        { value: "Supervisor", label: "Supervisor" },

      ],
    },
    {
      id: "function",
      name: "Job Function",
      options: [
        // Cities could be dynamically loaded based on the selected state
        { value: "Customer Service", label: "Customer Service" },
        { value: "Education", label: "Education" },
        { value: "Engineering", label: "Engineering" },
        { value: "Finance", label: "Finance" },
        { value: "Government", label: "Government" },
        { value: "Healthcare Services", label: "Healthcare Services" },
        { value: "Human Resources", label: "Human Resources" },
        { value: "IT", label: "IT" },
        { value: "Legal", label: "Legal" },
        { value: "Marketing", label: "Marketing" },
        { value: "Operations", label: "Operations" },
        { value: "Other", label: "Other" },
        { value: "Sales", label: "Sales" },

        // Add more cities as needed
      ],
    },
    
  ];
  
  export default filters;
  
